---

name: Problem
description: You have encountered problems when using the modules
title: "Problem: "
labels: ['problem', 'triage']

body:
  - type: markdown
    attributes:
      value: |
        Please make sure to go through these steps **before opening an issue**:

        - [ ] Read the documentation of the affected module: [Docs](https://github.com/ansibleguy/collection_opnsense/tree/latest/docs)

        - [ ] Read the troubleshooting info: [Info](https://github.com/ansibleguy/collection_opnsense#errors)

        - [ ] Check if there are existing [issues](https://github.com/ansibleguy/collection_opnsense/issues)
        or [discussions](https://github.com/ansible-semaphore/semaphore/discussions) regarding your topic

  - type: textarea
    id: modules
    attributes:
      label: Modules
      description: |
        What modules are affected?
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Version
      description: |
        What version of the Collection are you using?
        > Command: `ansible-galaxy collection list | grep opnsense`
      render: bash
    validations:
      required: true

  - type: textarea
    id: version-ansible
    attributes:
      label: Ansible Version
      description: |
        What version of Ansible & Python are you running?
        > Command: `ansible --version`
      render: bash
    validations:
      required: true

  - type: textarea
    id: version-opnsense
    attributes:
      label: OPNSense Version
      description: |
        What version of OPNSense are you running?
        Find it in the WebUI at 'System - Firmware - Status'
      render: bash
    validations:
      required: true

  - type: textarea
    id: version-opnsense-plugin
    attributes:
      label: OPNSense-Plugin Version
      description: |
        If the module targets a non-default plugin:
        What version of the OPNSense-Plugin are you running?
        Find it in the WebUI at 'System - Firmware - Plugins'
      render: bash
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Issue
      description: |
        Describe the problem you encountered and tell us what you would have expected to happen
    validations:
      required: true

  - type: textarea
    id: config-ansible
    attributes:
      label: Config Ansible
      description: |
        Please provide as the configuration you used when the error occurred!
      render: yaml
    validations:
      required: true

  - type: textarea
    id: config-opnsense
    attributes:
      label: Config OPNSense
      description: |
        Please provide as the configuration you used when the error occurred!
      render: bash
    validations:
      required: false

  - type: textarea
    id: output-debug
    attributes:
      label: Debug Output
      description: |
        Set the [debug option](https://opnsense.ansibleguy.net/en/latest/usage/4_develop.html#debugging) and copy its output.
      render: bash
    validations:
      required: true

  - type: textarea
    id: output-profiling
    attributes:
      label: Profiling Output
      description: |
        If the issue is related to time-consumption, you may also add the content of the
        [profiling logs](https://opnsense.ansibleguy.net/en/latest/usage/4_develop.html#profiling).
      render: bash
    validations:
      required: false
